sudo: false

language: node_js
node_js:
    - "0.12"

before_script:
  - npm install -g gulp
script: gulp test

cache:
  directories:
    - node_modules

after_success:
  - ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
